### ISSUE TITLE
Misunderstanding of ES6 rules

### ISSUE THREAD

**Issue by akachicon** [pandoracat/webpack-demos#1]
According to this [code](https://github.com/pandoracat/webpack-demos/blob/master/demos/09.hot-module-reload.03.hrm/src/index.js) it seems that you don't quite understand how js works. There is a rule in its spec that tells us that the scope for a function declaration is defined by the closest curly braces in which it's included. With that said consider the following example:
```
(function () {
    function f() {
        console.log('f');
    }
})();

f();	// f is not defined because of the ES6 scoping rules
```
This example demostrates the same approach you use in your code and I can't see how it could possibly get to work.

**Comment by pandoracat** [comment]
> According to this [code](https://github.com/pandoracat/webpack-demos/blob/master/demos/09.hot-module-reload.03.hrm/src/index.js) it seems that you don't quite understand how js works. There is a rule in its spec that tells us that the scope for a function declaration is defined by the closest curly braces in which it's included. With that said consider the following example:
> 
> ```
> (function () {
>     function f() {
>         console.log('f');
>     }
> })();
> 
> f();	// f is not defined because of the ES6 scoping rules
> ```
> This example demostrates the same approach you use in your code and I can't see how it could possibly get to work.

You are right, the getComponent function cannot be accessed in the hot module solution code.
